### ISSUE TITLE
ModuleNotFoundError: No module named 'pythonrc'

### ISSUE THREAD

**Issue by EnorMOZ** [greyblue9/unpyc37-3.10#2]
>>> from unpyc3 import decompile
.....
Adding opcode opname='DICT_MERGE' -> code=164
Adding opcode opname='DICT_UPDATE' -> code=165
>>> print (decompile("myfile.pyc"))
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/userA/scripts/unpyc37-3.10/unpyc/unpyc3.py", line 337, in decompile
    return dec_module(obj)
  File "/Users/userA/scripts/unpyc37-3.10/unpyc/unpyc3.py", line 327, in dec_module
    return code.get_suite(include_declarations=False, look_for_docstring=True)
  File "/Users/userA/scripts/unpyc37-3.10/unpyc/unpyc3.py", line 614, in get_suite
    dec.run()
  File "/Users/userA/scripts/unpyc37-3.10/unpyc/unpyc3.py", line 1943, in run
    new_addr = method(*args)
  File "/Users/userA/scripts/unpyc37-3.10/unpyc/unpyc3.py", line 2443, in IMPORT_NAME
    level, fromlist = self.stack.pop(2)
  File "/Users/userA/scripts/unpyc37-3.10/unpyc/unpyc3.py", line 427, in pop
    from pythonrc import at
ModuleNotFoundError: No module named 'pythonrc'
```

**Comment by greyblue9** [comment]
Sorry about this; fixed now!
