### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'opcode'

### ISSUE THREAD

**Issue by Wlbak** [greyblue9/unpyc37-3.10#31]
[zsxn.zip](https://github.com/greyblue9/unpyc37-3.10/files/13805217/zsxn.zip)
How to restore such confusion? When I restore it to the end, I will report an error
"AttributeError: 'NoneType' object has no attribute 'opcode'", I am not sure how to solve it, could you please help me? "

**Comment by jp-0** [comment]
Depending upon which opcode is causing you issues, you can add it to `SuiteDecompiler`.

e.g. using `JUMP_IF_NOT_EXC_MATCH`
For the time being I have worked around this by adding the following to `SuiteDecompiler` in `unpyc37-3.10/src/unpyc/unpyc3.py`
It is not ideal but does the job for what I need to allow rest of the decompilation to proceed.
Issue of trying to pop empty stack, but that appears customary of many of the other opcodes already implemented ...

```
    def JUMP_IF_NOT_EXC_MATCH(self, addr, target):
        exc_type = self.stack.pop()
        raised_exc = self.stack.pop()
        if not issubclass(raised_exc, exc_type):
            addr.jump(target)
        else:
            end_addr = addr.jump()
            self.push_popjump(True, end_addr, raised_exc, addr)
            d = SuiteDecompiler(addr[1], end_addr, self.stack)
            d.run()
            self.stack.pop()
            return end_addr
```

**Comment by JustGuardian** [comment]
> Depending upon which opcode is causing you issues, you can add it to `SuiteDecompiler`.
> 
> e.g. using `JUMP_IF_NOT_EXC_MATCH` For the time being I have worked around this by adding the following to `SuiteDecompiler` in `unpyc37-3.10/src/unpyc/unpyc3.py` It is not ideal but does the job for what I need to allow rest of the decompilation to proceed. Issue of trying to pop empty stack, but that appears customary of many of the other opcodes already implemented ...
> 
> ```
>     def JUMP_IF_NOT_EXC_MATCH(self, addr, target):
>         exc_type = self.stack.pop()
>         raised_exc = self.stack.pop()
>         if not issubclass(raised_exc, exc_type):
>             addr.jump(target)
>         else:
>             end_addr = addr.jump()
>             self.push_popjump(True, end_addr, raised_exc, addr)
>             d = SuiteDecompiler(addr[1], end_addr, self.stack)
>             d.run()
>             self.stack.pop()
>             return end_addr
> ```

Could you explain better how to add that code? I tried the fix that you suggested but I still get the same error.

**Comment by FreedomLabsIO** [comment]
```
python -m unpyc.unpyc3 main.pyc

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.py310venv/lib/python3.10/site-packages/unpyc/unpyc3.py", line 3824, in <module>
    code = Code(code_obj)
  File "/home/ubuntu/.py310venv/lib/python3.10/site-packages/unpyc/unpyc3.py", line 455, in __init__
    self.find_else()
  File "/home/ubuntu/.py310venv/lib/python3.10/site-packages/unpyc/unpyc3.py", line 513, in find_else
    jump_addr.opcode in else_jump_opcodes
AttributeError: 'NoneType' object has no attribute 'opcode'
```

I got this error because of 

`JUMP_IF_NOT_EXC_MATCH`

Adding the code to `SuiteDecompiler` did not fixed it.
