### ISSUE TITLE
Exception: Empty stack popped!

### ISSUE THREAD

**Issue by pp0236** [greyblue9/unpyc37-3.10#5]
```
Adding opcode opname='BUILD_SLICE' -> code=133
Adding opcode opname='MAKE_CLOSURE' -> code=134
Adding opcode opname='LOAD_CLOSURE' -> code=135
Adding opcode opname='LOAD_DEREF' -> code=136
Adding opcode opname='STORE_DEREF' -> code=137
Adding opcode opname='CALL_FUNCTION_VAR' -> code=140
Adding opcode opname='CALL_FUNCTION_KW' -> code=141
Adding opcode opname='CALL_FUNCTION_VAR_KW' -> code=142
Adding opcode opname='SETUP_WITH' -> code=143
Adding opcode opname='EXTENDED_ARG' -> code=145
Adding opcode opname='SET_ADD' -> code=146
Adding opcode opname='MAP_ADD' -> code=147
Traceback (most recent call last):
  File "C:\Users\D-Com\Desktop\loader - Copy.py", line 35, in <module>
    print(decompile(c.send_payloads))
  File "C:\Users\D-Com\Desktop\unpyc\unpyc3.py", line 1369, in __str__
    self.display(istr)
  File "C:\Users\D-Com\Desktop\unpyc\unpyc3.py", line 1580, in display
    self.display_undecorated(indent)
  File "C:\Users\D-Com\Desktop\unpyc\unpyc3.py", line 1606, in display_undecorated
    self.code.get_suite().display(indent + 1)
  File "C:\Users\D-Com\Desktop\unpyc\unpyc3.py", line 606, in get_suite
    dec.run()
  File "C:\Users\D-Com\Desktop\unpyc\unpyc3.py", line 1860, in run
    new_addr = method(*args)
  File "C:\Users\D-Com\Desktop\unpyc\unpyc3.py", line 1986, in SETUP_FINALLY
    end_finally = d_finally.run()
  File "C:\Users\D-Com\Desktop\unpyc\unpyc3.py", line 1860, in run
    new_addr = method(*args)
  File "C:\Users\D-Com\Desktop\unpyc\unpyc3.py", line 2201, in POP_TOP
    self.stack.pop().on_pop(self)
  File "C:\Users\D-Com\Desktop\unpyc\unpyc3.py", line 428, in pop
    val = self.pop1()
  File "C:\Users\D-Com\Desktop\unpyc\unpyc3.py", line 422, in pop1
    raise Exception('Empty stack popped!')
Exception: Empty stack popped!
```

**Comment by greyblue9** [comment]
Try again please

**Comment by greyblue9** [comment]
We added some more fault tolerance and fixed the logic in POP_JUMP_IF , hopefully these will help!
e.g. `python3 -m unpyc.unpyc3 file.pyc`

Partial decompilation (range):
`python3 -m unpyc.unpyc3 file.pyc 0 320`
`python3 -m unpyc.unpyc3 file.pyc 321`

**Comment by greyblue9** [comment]
let me know if you have a chance to test the new master, sorry it took so long !  😁 @pp0236

**Comment by pp0236** [comment]
i dont even know i made this issue lol
i will try later thanks
